# CPU-optimized Docker Compose for Code du Travail AI Assistant
# Use this file for CPU-only instances: docker-compose -f docker-compose.cpu.yml up -d

services:
  telegram-bot:
    build: .
    container_name: code-du-travail-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MODEL_NAME=${MODEL_NAME:-Pyzeur/Code-du-Travail-mistral-finetune}
      - DEVICE=cpu  # Force CPU usage
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - HUGGING_FACE_TOKEN=${HUGGING_FACE_TOKEN}
      # Email settings for docker-mailserver
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_DOMAIN=${EMAIL_DOMAIN}
      - IMAP_HOST=mailserver
      - IMAP_PORT=993
      - SMTP_HOST=mailserver
      - SMTP_PORT=587
      # CPU optimization settings
      - USE_QUANTIZATION=true
      - LOAD_IN_4BIT=true
      - EMAIL_MAX_TOKENS=1000  # Reduced for CPU
      - TELEGRAM_MAX_TOKENS=256  # Reduced for CPU
    volumes:
      - ./logs:/app/logs
      - ./cache:/root/.cache  # For model caching
    depends_on:
      - mailserver
    networks:
      - mail-network
    # CPU resource limits for better performance
    deploy:
      resources:
        limits:
          memory: 3G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    stdin_open: true
    tty: true

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.${EMAIL_DOMAIN}
    restart: unless-stopped
    ports:
      - "25:25"    # SMTP
      - "143:143"  # IMAP
      - "587:587"  # SMTP submission
      - "993:993"  # IMAP SSL
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/letsencrypt/live/mail.cryptomaltese.com/fullchain.pem:/tmp/docker-mailserver/ssl/mail.cryptomaltese.com-cert.pem:ro
      - /etc/letsencrypt/live/mail.cryptomaltese.com/privkey.pem:/tmp/docker-mailserver/ssl/mail.cryptomaltese.com-key.pem:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_MANAGESIEVE=1
      - POSTMASTER_ADDRESS=postmaster@${EMAIL_DOMAIN}
      - SSL_TYPE=letsencrypt
      - LETSENCRYPT_DOMAIN=${LETSENCRYPT_DOMAIN:-mail.cryptomaltese.com}
      - PERMIT_DOCKER=network
      - SPOOF_PROTECTION=1
      - ENABLE_SRS=1
      - ONE_DIR=1
      - DMS_DEBUG=0
      - LOG_LEVEL=info
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      - mail-network

networks:
  mail-network:
    driver: bridge 