version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: code-du-travail-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MODEL_NAME=Pyzeur/Code-du-Travail-mistral-finetune
      - DEVICE=auto
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./cache:/root/.cache  # For model caching
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true