#!/bin/bash

echo "[INFO] Comprehensive Ubuntu DNS Fix for Docker"
echo "[STEP] Checking current DNS configuration..."

# Check current DNS configuration
echo "Current DNS configuration:"
cat /etc/resolv.conf

echo "[STEP] Configuring system DNS..."

# Backup current resolv.conf
sudo cp /etc/resolv.conf /etc/resolv.conf.backup

# Create a more robust resolv.conf
sudo tee /etc/resolv.conf > /dev/null <<EOF
# Generated by fix_ubuntu_dns.sh
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 1.1.1.1
nameserver 208.67.222.222
options timeout:2 attempts:3 rotate
EOF

echo "[STEP] Making resolv.conf immutable to prevent overwrites..."
sudo chattr +i /etc/resolv.conf

echo "[STEP] Testing DNS resolution..."
nslookup deb.debian.org

echo "[STEP] Configuring Docker daemon DNS..."

# Create Docker daemon configuration
sudo mkdir -p /etc/docker
sudo tee /etc/docker/daemon.json > /dev/null <<EOF
{
  "dns": ["8.8.8.8", "8.8.4.4", "1.1.1.1"],
  "dns-opts": ["timeout:2", "attempts:3"],
  "max-concurrent-downloads": 10,
  "max-concurrent-uploads": 5,
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  },
  "storage-driver": "overlay2"
}
EOF

echo "[STEP] Restarting Docker daemon..."
sudo systemctl restart docker

echo "[STEP] Waiting for Docker to be ready..."
sleep 10

echo "[STEP] Testing Docker DNS resolution..."
docker run --rm alpine nslookup deb.debian.org

echo "[STEP] Cleaning Docker system..."
docker system prune -af

echo "[INFO] DNS fix completed!"
echo "[INFO] If you need to revert DNS changes: sudo chattr -i /etc/resolv.conf && sudo cp /etc/resolv.conf.backup /etc/resolv.conf" 