#!/bin/bash

echo "[INFO] Debian 11 DNS Fix for Docker with Cloudflare/Infomaniak Setup"
echo "[STEP] Checking current DNS configuration..."

# Check current DNS configuration
echo "Current DNS configuration:"
cat /etc/resolv.conf

echo "[STEP] Configuring system DNS for Cloudflare/Infomaniak setup..."

# Backup current resolv.conf
sudo cp /etc/resolv.conf /etc/resolv.conf.backup

# Create a more robust resolv.conf optimized for Cloudflare
sudo tee /etc/resolv.conf > /dev/null <<EOF
# Generated by fix_debian_dns.sh for Cloudflare/Infomaniak setup
# Primary: Cloudflare DNS
nameserver 1.1.1.1
nameserver 1.0.0.1
# Secondary: Google DNS (fallback)
nameserver 8.8.8.8
nameserver 8.8.4.4
# Options for better performance
options timeout:2 attempts:3 rotate
EOF

echo "[STEP] Making resolv.conf immutable to prevent overwrites..."
sudo chattr +i /etc/resolv.conf

echo "[STEP] Testing DNS resolution..."
echo "Testing Cloudflare DNS resolution:"
nslookup cryptomaltese.com

echo "[STEP] Configuring Docker daemon DNS for Cloudflare..."

# Create Docker daemon configuration optimized for Cloudflare
sudo mkdir -p /etc/docker
sudo tee /etc/docker/daemon.json > /dev/null <<EOF
{
  "dns": ["1.1.1.1", "1.0.0.1", "8.8.8.8"],
  "dns-opts": ["timeout:2", "attempts:3"],
  "max-concurrent-downloads": 10,
  "max-concurrent-uploads": 5,
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  },
  "storage-driver": "overlay2"
}
EOF

echo "[STEP] Restarting Docker daemon..."
sudo systemctl restart docker

echo "[STEP] Waiting for Docker to be ready..."
sleep 10

echo "[STEP] Testing Docker DNS resolution..."
docker run --rm alpine nslookup deb.debian.org

echo "[STEP] Testing Docker resolution for your domain..."
docker run --rm alpine nslookup cryptomaltese.com

echo "[STEP] Cleaning Docker system..."
docker system prune -af

echo "[INFO] DNS fix completed for Cloudflare/Infomaniak setup!"
echo "[INFO] If you need to revert DNS changes: sudo chattr -i /etc/resolv.conf && sudo cp /etc/resolv.conf.backup /etc/resolv.conf"
echo "[INFO] Your domain cryptomaltese.com should now resolve properly in Docker containers" 